# Lab 2 - Data Imputation

## Langkah 0 - Persiapan

In [30]:
import pandas as pd
import numpy as np

print('Library loaded OK')

Library loaded OK

## Langkah 1 - Memuat Data

In [24]:
from google.colab import drive
drive.mount('/content/drive')
path = '/content/drive/MyDrive/MachineLearning/Titanic-Dataset.csv'

df = pd.read_csv(path)
df.head()

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

## Langkah 2 - Inspeksi Data

In [25]:
# Inspeksi singkat: cek data hilang sebelum imputasi
df.info()
print()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

## Langkah 3 - Data Imputation

In [26]:

df['Age'].fillna(value=df['Age'].mean(), )

df['Cabin'].fillna(value='DECK', )

df['Embarked'].fillna(value=df['Embarked'].mode()[0],)

print('Imputasi selesai')

Imputasi selesai

/tmp/ipykernel_1980/444975385.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Age'].fillna(value=df['Age'].mean(), inplace=True)
/tmp/ipykernel_1980/444975385.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Cabin'].fillna(value='DECK', inplace=True)
/tmp/ipykernel_1980/444975385.py:10: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Embarked'].fillna(value=df['Embarked'].mode()[0], inplace=True)

## Langkah 4 - Validasi Hasil

In [27]:
# Cek kembali apakah data hilang sudah terisi
df.info()
print()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          891 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        891 non-null    object
 11  Embarked     891 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
dtype: int64

In [28]:
# Validasi langsung: cek nilai yang baru diisi (Age, Cabin, Embarked)
print('Age mean  :', df['Age'].mean())
print('Cabin mode:', df['Cabin'].value_counts().idxmax())
print('Emb modus :', df['Embarked'].value_counts().idxmax())
print()
df[['Age', 'Cabin', 'Embarked']].head()

Age mean  : 29.69911764705882
Cabin mode: DECK
Emb modus : S

    Age Cabin Embarked
0  22.0  DECK        S
1  38.0   C85        C
2  26.0  DECK        S
3  35.0  C123        S
4  35.0  DECK        S

## (Opsional) Simpan Hasil

In [29]:
# Simpan hasil imputasi untuk tahapan selanjutnya
df.to_csv('Titanic-Dataset-Fixed.csv', index=False)
print('Tersimpan: Titanic-Dataset-Fixed.csv')

Tersimpan: Titanic-Dataset-Fixed.csv